baseURL = "https://yrs-ago.github.io"
languageCode = "en-us"
title = "Jonathan Hicks"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/projects"
  weight = 2

[[menu.main]]
  name = "Bytes"
  url = "/bytes"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 5

[[menu.main]]
  name = "Resume"
  url = "https://raw.githubusercontent.com/yrs-ago/yrs-ago.github.io/b1a9084d763fb30377b4e35501610e2ca364294b/Jonathan%20Hicks%20-%20Resume%202025.pdf"
  weight = 6

[[menu.main]]
  name = "Misc"
  url = "/misc"
  weight = 7

# https://gohugo.io/getting-started/configuration-markup
[markup]

  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "monokai"
    tabWidth = 4
    lineAnchors = ""
    anchorLineNos = false
  
  [markup.goldmark.renderer]
    unsafe= true  # allow md+html mix

[params]
  author = "Jonathan Hicks"
  colortheme = "dark"

  dateFormat = "2006-01-02"
  showReadTime = true
  tocInline = false
  # logo = 

  # Home page settings
  tagsOverview = false
  showProjectsList = true

  [params.links]
    beatstars = "https://www.beatstars.com/elixrrrr"
    spotify = "https://open.spotify.com/artist/79Sjdt0dmZ77tgIAiaEAXS?si=qPrHyWR4SEOP4mD6PZfUxQ"
    ogsoundcloud = "https://soundcloud.com/elixrrrr"
    soundcloud = "https://soundcloud.com/yrs-ago"
    gmail = "jonhicks909@gmail.com"
    github = "https://github.com/yrs-ago"
    linkedin = "https://www.linkedin.com/in/jonathancharleshicks/"
    resume = "https://raw.githubusercontent.com/yrs-ago/yrs-ago.github.io/b1a9084d763fb30377b4e35501610e2ca364294b/Jonathan%20Hicks%20-%20Resume%202025.pdf"
